// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAClrTQ6-Ee3Bfo-Bfu0qNJXHxK64gZj7M',
    appId: '1:271405819649:web:8f00f448d04be12eb91d00',
    messagingSenderId: '271405819649',
    projectId: 'shoppay-17570',
    authDomain: 'shoppay-17570.firebaseapp.com',
    storageBucket: 'shoppay-17570.firebasestorage.app',
    measurementId: 'G-MKWM793KJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgxIEEza4R0qJDGxZI01kkrKY9uPrECfI',
    appId: '1:271405819649:android:9317e4646874f487b91d00',
    messagingSenderId: '271405819649',
    projectId: 'shoppay-17570',
    storageBucket: 'shoppay-17570.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpZt6TB-YS-uck6PXWTRU1E-fFn2IOyeE',
    appId: '1:271405819649:ios:c56e45a9d1d5216cb91d00',
    messagingSenderId: '271405819649',
    projectId: 'shoppay-17570',
    storageBucket: 'shoppay-17570.firebasestorage.app',
    iosBundleId: 'com.example.shopee2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpZt6TB-YS-uck6PXWTRU1E-fFn2IOyeE',
    appId: '1:271405819649:ios:c56e45a9d1d5216cb91d00',
    messagingSenderId: '271405819649',
    projectId: 'shoppay-17570',
    storageBucket: 'shoppay-17570.firebasestorage.app',
    iosBundleId: 'com.example.shopee2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAClrTQ6-Ee3Bfo-Bfu0qNJXHxK64gZj7M',
    appId: '1:271405819649:web:8ed03da1c1a84fe2b91d00',
    messagingSenderId: '271405819649',
    projectId: 'shoppay-17570',
    authDomain: 'shoppay-17570.firebaseapp.com',
    storageBucket: 'shoppay-17570.firebasestorage.app',
    measurementId: 'G-LYN5S20V3Y',
  );
}